name: Auth

on:
  push:
    branches:
      - auth
  pull_request:
    branches:
      - auth

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Move env inside the job
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run test
        run: npm run test
        working-directory: ./server

      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.157.154.176 << 'EOF'
          cd /home/ec2-user/vaultify
          git pull origin auth
          npm install
          cd server
          npm run dev
          EOF
