name: Auth

on:
  push:
    branches:
      - auth
  pull_request:
    branches:
      - auth

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Move env inside the job
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: 4000

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run test
        run: npm run test
        working-directory: ./server

      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          EC2_SSH_KEY: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.157.154.176 << 'EOF'
          ls
          cd vaultify
          git pull origin auth
          cd server
          npm install
           # Create or update .env file
          cat <<EOT > .env
          DATABASE_URL="mongodb+srv://owoyemiameed:vaultify_20000@vaultify.wuiwj.mongodb.net/vaultify?retryWrites=true&w=majority&appName=vaultify"
          NODE_ENV=development
          CLIENT_URL=http://localhost:3000
          PORT=8000
          EOT

          # Restart the server (change this if using PM2 or another process manager)
          npm run dev &
          EOF
